//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Oxygene Version: 2.0.0.398
//     Runtime Version: 2.0.50727.1318
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

{$HIDE PW12}

namespace DLinq.Properties;

interface

type
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute]
    [System.CodeDom.Compiler.GeneratedCodeAttribute('Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator', '9.0.0.0')]
    Settings = partial class(System.Configuration.ApplicationSettingsBase)
        private 
            class var defaultInstance: Settings := (System.Configuration.ApplicationSettingsBase.Synchronized(new Settings()) as Settings);
            class method get_Default: Settings;
            method get_NorthwindConnectionString: System.String;
            method get_NorthwindConnectionString1: System.String;
        public 
            class property Default: Settings read get_Default;
            [System.Configuration.ApplicationScopedSettingAttribute]
            [System.Diagnostics.DebuggerNonUserCodeAttribute]
            [System.Configuration.SpecialSettingAttribute(System.Configuration.SpecialSetting.ConnectionString)]
            [System.Configuration.DefaultSettingValueAttribute('Data Source=localhost;Initial Catalog=Northwind;Integrated Security=SSPI')]
            property NorthwindConnectionString: System.String read get_NorthwindConnectionString;
            [System.Configuration.ApplicationScopedSettingAttribute]
            [System.Diagnostics.DebuggerNonUserCodeAttribute]
            [System.Configuration.SpecialSettingAttribute(System.Configuration.SpecialSetting.ConnectionString)]
            [System.Configuration.DefaultSettingValueAttribute('Data Source=localhost;Initial Catalog=Northwind;Integrated Security=SSPI')]
            property NorthwindConnectionString1: System.String read get_NorthwindConnectionString1;
    end;
    
implementation

{ Settings }

class method Settings.get_Default: Settings;
begin
    exit(defaultInstance);
end;

method Settings.get_NorthwindConnectionString: System.String;
begin
    exit((self['NorthwindConnectionString'] as System.String));
end;

method Settings.get_NorthwindConnectionString1: System.String;
begin
    exit((self['NorthwindConnectionString1'] as System.String));
end;

end.
