// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SharedUI.WPF.Properties {


	[System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("RemObjects.Fire.ManagedHelper.SettingsCodeGeneratorTool", "1.0.0.0")]
	internal sealed partial class Settings : System.Configuration.ApplicationSettingsBase {

		private static Settings defaultInstance = ((Settings)(System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

		static Settings Default {
			get {
				return Settings.defaultInstance;
			}
		}
	}
}